### ISSUE TITLE
Stop from using addr_adv

### ISSUE THREAD

**Issue by joaomeira26** [multipath-tcp/mptcpd#162]
Hello,

I'm making a plugin that needs to configure the endpoints, but since the path manager addr_adv listens to added local address events, it always configures the endpoints, even if I don't want it to happen. 

That being said, is there a way to make mptcpd not use the addr_adv path manager, something else than removing addr_adv from the plugin directory?

**Comment by ossama-othman** [comment]
> Considering that I need this, do you mind if I take care of it?

Not at all.  Thanks for your help!
