### ISSUE TITLE
Configure mptcpd

### ISSUE THREAD

**Issue by AlejandraOliver** [multipath-tcp/mptcpd#280]
Hi, I'm using mptcpd and I don't how to tell the daemon that I want a certain path to be a backup path.
Any suggestions??

Thanks!!!

**Comment by matttbe** [comment]
Hello,

To best to get more help for mptcpd is to look at the man page (`man mptcpd`).
If you want to change the configuration, it will tell you to look at `/etc/mptcpd/mptcpd.conf` file which is "self-documented". You can then tell the daemon to create endpoints with specific flags (for all endpoints):

https://github.com/multipath-tcp/mptcpd/blob/863e83f255f55dfd0ba9325d816bd99f6d9da0c2/etc/mptcpd.conf.in#L31-L46

Just to be clear, mptcpd is supposed to be used with plugins that can be built to serve some specific purposes using the [C API](https://mptcpd.mptcp.dev/doc/html/). By default, it comes with plugins that will tell the in-kernel path-manager to use all available IP as endpoint to create subflows (client use-case then). The configuration can be easily modified to flag all endpoints as `signal` instead (server use-case).

The advantage of the default configuration is that it automatically adds endpoints. But it might not serve all purposes, especially if you need more flexibility. Then the alternatives are:
- use the in-kernel path-manager without `mptcpd` and configure the endpoints manually (or with the help of NetworkManager >=1.40)
- use the userspace path-manager (`sysctl net.mptcp.pm_type=1`) with `mptcpd` and a plugin, e.g. sspi: _single-subflow-per-interface_ path manager plugin or a custom one.

With the in-kernel PM, all connections (per netns) will have the same behaviour: likely what most people need. While with the userspace PM, it is possible to have different behaviours per connection: to server some specific use-cases.

**Comment by AlejandraOliver** [comment]
Once I have change de mptcpd.conf, I need to do something to save the new configuration?

**Comment by AlejandraOliver** [comment]
I have modified the mptcpd.conf as below (client side) :

~~~
[core]
# -------------------------
# Default logging mechanism
# -------------------------
#   stderr  - standard unbuffered I/O stream
#   syslog  - POSIX based system logger
#   journal - systemd Journal
#   null    - disable logging
log=@mptcpd_logger@

# ----------------
# Plugin directory
# ----------------
plugin-dir=@pkglibdir@

# -------------------
# Path manager plugin
# ---------------------
# The plugin found with the most favorable (lowest) priority will be
# used if one is not specified.
path-manager=@mptcpd_default_pm@

# --------------------------
# Address announcement flags
# --------------------------
# A comma separated list containing one or more of the flags:
#
#   subflow
#   signal    (do not use with the "fullmesh" flag)
#   backup
#   fullmesh  (do not use with the "signal" flag)
#
# Plugins that deal with the in-kernel path manager may use these
# flags when advertising addresses.
#
# See the ip-mptcp(8) man page for details.
#
addr-flags=subflow fullmesh

# --------------------------
# Address notification flags
# --------------------------
# A comma separated list containing one or more of the flags:
#
#   existing
#     Notify plugins of the addresses that exist at mptcpd start
#
#   skip_link_local
#     Ignore (do not notify) [ipv6] link local address updates
#
#   skip_loopback
#     Ignore (do not notify) host (loopback) address updates
#
# These flags determine whether mptpcd plugins will be notified when
# related addresses are updated.
#
notify-flags=existing,skip_link_local,skip_loopback

# --------------------------
# Plugins to load
# --------------------------
# A comma separated list containing one or more plugins to load.
#
load-plugins=addr_adv,sspi

~~~

but I have only one subflow instead of all of them (using default scheduler).

**Comment by AlejandraOliver** [comment]
I emphasize that the problem is not routing because with `ip mptcp` it works correctly, so it must be the configuration of mptcpd.

**Comment by matttbe** [comment]
> Hello, I have modified the mptcpd.conf as below (client side) :

Mmh, you are not supposed to use the `.conf.in` file but modify the file that is installed in `/etc/mptcpd/mptcpd.conf` on your side. The version you sent still has the `@<...>@` that needs to be replaced by correct paths.

Also:

> 

> # --------------------------
> # Address announcement flags
> # --------------------------
> # A comma separated list containing one or more of the flags:
>
> # (...)
>
> #
> addr-flags=subflow fullmesh

that's not a "comma separated list".

> but I have only one subflow instead of all of them 

You can list the endpoints set by `mptcpd` using:

```
ip mptcp endpoint
```

and check if it is what you want.

> (using default scheduler).

The packet scheduler is in charge of scheduling packets, not opening/closing subflows. You can see how many **extra** subflows have been created used with `ss -Ma`

>  In the server side I have the same but with addr-flags=signal, instead of addr-flags=subflow fullmesh

Please check mptcp endpoints and mptcpd logs because the config file don't seem correct.

```
ip mptcp endpoint
sudo journalctl -u mptcp
```

**Comment by AlejandraOliver** [comment]
> The version you sent still has the @<...>@ that needs to be replaced by correct paths.

you mean change the following to a directory? but which one? I don't get it.
~~~
# ----------------
# Plugin directory
# ----------------
plugin-dir=@pkglibdir@
~~~

**Comment by matttbe** [comment]
> you mean change the following to a directory? but which one? I don't get it.

I don't know: you need to modify the file on your device, not overwriting it with the content from elsewhere.
I guess the easiest is to uninstall and re-install mptcpd.

Just in case, here is the original content of the file on Debian:

```
# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (c) 2018-2019, 2021-2022, Intel Corporation

# ------------------------------------------------------------------
#                     mptcpd Configuration File
# ------------------------------------------------------------------

[core]
# -------------------------
# Default logging mechanism
# -------------------------
#   stderr  - standard unbuffered I/O stream
#   syslog  - POSIX based system logger
#   journal - systemd Journal
#   null    - disable logging
log=stderr

# ----------------
# Plugin directory
# ----------------
plugin-dir=/usr/lib/x86_64-linux-gnu/mptcpd

# -------------------
# Path manager plugin
# ---------------------
# The plugin found with the most favorable (lowest) priority will be
# used if one is not specified.
path-manager=addr_adv

# --------------------------
# Address announcement flags
# --------------------------
# A comma separated list containing one or more of the flags:
#
#   subflow
#   signal    (do not use with the "fullmesh" flag)
#   backup
#   fullmesh  (do not use with the "signal" flag)
#
# Plugins that deal with the in-kernel path manager may use these
# flags when advertising addresses.
#
# See the ip-mptcp(8) man page for details.
#
# addr-flags=subflow

# --------------------------
# Address notification flags
# --------------------------
# A comma separated list containing one or more of the flags:
#
#   existing
#     Notify plugins of the addresses that exist at mptcpd start
#
#   skip_link_local
#     Ignore (do not notify) [ipv6] link local address updates
#
#   skip_loopback
#     Ignore (do not notify) host (loopback) address updates
#
# These flags determine whether mptpcd plugins will be notified when
# related addresses are updated.
#
# notify-flags=existing,skip_link_local,skip_loopback

# --------------------------
# Plugins to load
# --------------------------
# A comma separated list containing one or more plugins to load.
#
# load-plugins=addr_adv,sspi
```

**Comment by AlejandraOliver** [comment]
Ok! Thanks!

**Comment by matttbe** [comment]
> And, why the daemon creates as endpoints the MAC addresses of the interfaces, in addition to their IPs?

Probably because you have these IP(v6) on your system.

With IPv6, you will have link-local addresses (fe80::/10) created automatically and using the MAC address to be "unique": https://en.wikipedia.org/wiki/Link-local_address

I guess I can close this old ticket. Feel free to-reopen it if needed.
