### ISSUE TITLE
please rename mptcpd 'master' branch to 'main'

### ISSUE THREAD

**Issue by dcaratti** [multipath-tcp/mptcpd#289]
many open-source projects are gradually transitioning their 'master' branch to a less inconvenient name ('main' or similar) [1] [2]. Any objections to transition mptcpd as well?

(BTW, I see that the kernel code can be made 'compliant' with a 3-line patch, I can follow-up on the ML if you don't disagree)

[1] https://lore.kernel.org/git/pull.656.v4.git.1593009996.gitgitgadget@gmail.com/
[2] https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by mjmartineau** [comment]
I've renamed the default branch to `main` (to update references in github PRs and such).

For now, `master` is still pointing to the same git commit. After a transition period we can remove that reference.

**Comment by ossama-othman** [comment]
Thanks for suggesting and making this change!

**Comment by matttbe** [comment]
I suggest removing the `master` branch to avoid confusions: it was no longer up to date.

For people still using the `master` branch, please switch to the `main` one. Or rename it:

```
git switch master
git branch -M main
git branch --set-upstream-to=origin/main
```
