### ISSUE TITLE
Re-create subflow after ISP brake and restored

### ISSUE THREAD

**Issue by GusevVictor** [multipath-tcp/mptcpd#291]
Dear all, looking create_on_err  or anything else for auto recreate subflows. Is it possible to achieve that with mptcpd?
 
In the old doc it was in a separate mptcp module, but I don't understand where I can create it or found it in a new kernel (after v 5.6 - for example 6.8 in ubuntu 24.04). 
 
 
New in v0.92: If you want to re-create subflows after a timeout (e.g., if the NAT-mapping was lost due to idle-time), you can set /sys/module/mptcp_fullmesh/parameters/create_on_err to 1.
 
Best regards.

**Comment by matttbe** [comment]
Duplicated: https://lore.kernel.org/mptcp/20240611152044.3q6OMIkD@mail-nwsmtp-smtp-production-main-87.sas.yp-c.yandex.net/T/#u
