### ISSUE TITLE
make listening socket creation optional for userspace path manager plugins

### ISSUE THREAD

**Issue by marco-a-itl** [multipath-tcp/mptcpd#296]
**Is your feature request related to a problem? Please describe.**
When a plugin needs to advertise a new additional address calling `mptcpd_pm_add_addr()`, the mptcpd daemon automatically creates a new listening socket by calling `mptcpd_lm_listen()` in `upstream_announce()`.
In my use case, I have an external application which already has (two) listening sockets opened (which I want to advertise), and so the listener creation executed by mptcpd fails because address:port is already in use.

**Describe the solution you'd like**
Add a boolean parameter to `mptcpd_pm_add_addr()` to control the creation of listening sockets.

**Comment by matttbe** [comment]
Hi Marco,

Indeed, there should be a parameter to control the creation of listening sockets. It looks like Ossama suggested that a few years ago, when he looked at supporting these listening sockets: https://github.com/multipath-tcp/mptcpd/issues/223#issuecomment-1157258712

Any contributions are appreciated ;)
